### ISSUE TITLE
Название класса тестов должно совпадать с именем класса который мы тестируем

### ISSUE THREAD

**Issue by boris-dev** [DariaMitrofanovna/liga-internship#2]
https://github.com/DariaMitrofanovna/liga-internship/blob/2aa405892a451ae6fe026112599b0841d23cb1bd/javacore-song-task/src/test/java/ru/liga/Tests.java#L18

Ctrl+Shift+T и идея сама предложит создать тест с правильным именем

**Comment by DariaMitrofanovna** [comment]
Исправлено
