### ISSUE TITLE
Не понимаю что тестирую

### ISSUE THREAD

**Issue by boris-dev** [DariaMitrofanovna/liga-internship#3]
https://github.com/DariaMitrofanovna/liga-internship/blob/2aa405892a451ae6fe026112599b0841d23cb1bd/javacore-song-task/src/test/java/ru/liga/Tests.java#L63

Должно быть понятно откуда этот метод.

**Comment by boris-dev** [comment]
Имею ввиду,  что нужно писать класс из которого этот метод.
Analisys.getDiapason()
например

**Comment by DariaMitrofanovna** [comment]
Исправлено
