### ISSUE TITLE
HashMap слева

### ISSUE THREAD

**Issue by boris-dev** [DariaMitrofanovna/liga-internship#4]
https://github.com/DariaMitrofanovna/liga-internship/blob/2aa405892a451ae6fe026112599b0841d23cb1bd/javacore-song-task/src/main/java/ru/liga/AnalyzeVoice.java#L148

Конкретные классы коллекций в объявлении переменных и возвращаемых типов очень режут глаз.
Нужно использовать интерфейс Map.

**Comment by DariaMitrofanovna** [comment]
Исправлено
