### ISSUE TITLE
Класс делает слишком много всего

### ISSUE THREAD

**Issue by boris-dev** [DariaMitrofanovna/liga-internship#5]
https://github.com/DariaMitrofanovna/liga-internship/blob/2aa405892a451ae6fe026112599b0841d23cb1bd/javacore-song-task/src/main/java/ru/liga/AnalyzeVoice.java#L20

https://ru.wikipedia.org/wiki/%D0%91%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82

**Comment by DariaMitrofanovna** [comment]
Исправлено
