### ISSUE TITLE
Метод возвращает диапазон, но он не используется

### ISSUE THREAD

**Issue by boris-dev** [DariaMitrofanovna/liga-internship#6]
https://github.com/DariaMitrofanovna/liga-internship/blob/2aa405892a451ae6fe026112599b0841d23cb1bd/javacore-song-task/src/main/java/ru/liga/AnalyzeVoice.java#L111

Также присутствует смешение ответственности, ведь это бизнес логи, ради них делается задача.

Нужно разделить запись в логи и логику вытаскивания диапазона.

**Comment by DariaMitrofanovna** [comment]
Исправлено
