### ISSUE TITLE
Возвращаем значение, но не используем его.

### ISSUE THREAD

**Issue by boris-dev** [DariaMitrofanovna/liga-internship#7]
https://github.com/DariaMitrofanovna/liga-internship/blob/fd36d75a581084c20aff1886a40bb25234cf3e30/javacore-song-task/src/main/java/ru/liga/AnalyzeVoice.java#L38

Также пропало логирование, т.е. код уже не выполняет задачу

**Comment by DariaMitrofanovna** [comment]
Исправлено
